import React,{useState} from "react";
import {Alert,KeyboardAvoidingView,Platform,ScrollView,StyleSheet,Text,View} from "react-native";
import {Link,router} from "expo-router";
import {Ionicons} from "@expo/vector-icons";
import {Screen} from "@/components/Screen";
import {AppButton} from "@/components/AppButton";
import {AppInput} from "@/components/AppInput";
import {useAuth} from "@/context/AuthContext";
import {getApiErrorMessage} from "@/lib/api";
import {colors} from "@/constants/theme";
export default function Register(){const {signUp}=useAuth();const [name,setName]=useState("");const [email,setEmail]=useState("");const [phone,setPhone]=useState("");const [password,setPassword]=useState("");const [confirm,setConfirm]=useState("");const [loading,setLoading]=useState(false);async function submit(){if(!name.trim()||!email.trim()||!phone.trim()||!password){Alert.alert("Missing information","Complete all required fields.");return;}if(password.length<8){Alert.alert("Password too short","Password must contain at least 8 characters.");return;}if(password!==confirm){Alert.alert("Passwords do not match","Enter the same password twice.");return;}try{setLoading(true);await signUp({name:name.trim(),email:email.trim().toLowerCase(),phone:phone.trim(),password});router.replace("/(app)/home");}catch(e){Alert.alert("Registration failed",getApiErrorMessage(e));}finally{setLoading(false);}}
 return <Screen><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==="ios"?"padding":undefined}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><View style={styles.top}><View style={styles.logo}><Ionicons name="sparkles" size={22} color={colors.champagne}/></View><Text style={styles.brand}>Salon.</Text></View><Text style={styles.title}>Create your account</Text><Text style={styles.subtitle}>Join Salon. and manage your beauty appointments with ease.</Text><AppInput label="Full name" value={name} onChangeText={setName} placeholder="Your name" autoCapitalize="words"/><AppInput label="Email" value={email} onChangeText={setEmail} placeholder="you@example.com" keyboardType="email-address"/><AppInput label="Phone" value={phone} onChangeText={setPhone} placeholder="+92 300 1234567" keyboardType="phone-pad"/><AppInput label="Password" value={password} onChangeText={setPassword} placeholder="At least 8 characters" secureTextEntry/><AppInput label="Confirm password" value={confirm} onChangeText={setConfirm} placeholder="Repeat your password" secureTextEntry/><AppButton title="Create account" onPress={submit} loading={loading}/><View style={styles.footer}><Text style={styles.footerText}>Already have an account? </Text><Link href="/(auth)/login" style={styles.link}>Log in</Link></View></ScrollView></KeyboardAvoidingView></Screen>}
const styles=StyleSheet.create({content:{flexGrow:1,paddingVertical:28},top:{alignItems:"center",marginBottom:25},logo:{width:54,height:54,borderRadius:18,backgroundColor:colors.plum,alignItems:"center",justifyContent:"center"},brand:{fontFamily:"Georgia",fontSize:26,color:colors.plum,marginTop:6},title:{color:colors.ink,fontSize:28,fontWeight:"900",textAlign:"center"},subtitle:{color:colors.muted,fontSize:14,lineHeight:21,textAlign:"center",marginTop:5,marginBottom:25},footer:{flexDirection:"row",justifyContent:"center",marginTop:24,marginBottom:20},footerText:{color:colors.muted,fontSize:12},link:{color:colors.plum,fontWeight:"900",fontSize:12}});
