"""add booking and slot tables

Revision ID: abed93a34537
Revises: b3fdf7a42891
Create Date: 2026-08-18 16:31:43.951015

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'abed93a34537'
down_revision: Union[str, Sequence[str], None] = 'b3fdf7a42891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salon_slots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('salon_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('slot_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'slot_date', 'start_time', name='uq_agent_slot_date_start')
    )
    op.create_index(op.f('ix_salon_slots_agent_id'), 'salon_slots', ['agent_id'], unique=False)
    op.create_index(op.f('ix_salon_slots_salon_id'), 'salon_slots', ['salon_id'], unique=False)
    op.create_index(op.f('ix_salon_slots_slot_date'), 'salon_slots', ['slot_date'], unique=False)
    op.create_index(op.f('ix_salon_slots_status'), 'salon_slots', ['status'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_number', sa.String(length=40), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('salon_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['salon_slots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slot_id')
    )
    op.create_index(op.f('ix_bookings_agent_id'), 'bookings', ['agent_id'], unique=False)
    op.create_index(op.f('ix_bookings_booking_date'), 'bookings', ['booking_date'], unique=False)
    op.create_index(op.f('ix_bookings_booking_number'), 'bookings', ['booking_number'], unique=True)
    op.create_index(op.f('ix_bookings_customer_id'), 'bookings', ['customer_id'], unique=False)
    op.create_index(op.f('ix_bookings_salon_id'), 'bookings', ['salon_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_table('booking_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('bundle_id', sa.Integer(), nullable=True),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bundle_id'], ['bundles.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_items_booking_id'), 'booking_items', ['booking_id'], unique=False)
    op.alter_column('bundles', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('bundles', 'original_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('bundles', 'bundle_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('salons', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('salons', 'address_line1',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column(
        "salons",
        "opening_time",
        existing_type=sa.VARCHAR(length=5),
        type_=sa.Time(),
        existing_nullable=False,
        postgresql_using="opening_time::time without time zone",
    )
    op.alter_column(
        "salons",
        "closing_time",
        existing_type=sa.VARCHAR(length=5),
        type_=sa.Time(),
        existing_nullable=False,
        postgresql_using="closing_time::time without time zone",
    )
    op.alter_column('services', 'name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('services', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('services', 'price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_service_salon_name'), 'services', type_='unique')
    op.drop_constraint(op.f('users_salon_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'salons', ['salon_id'], ['id'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_salon_id_fkey'), 'users', 'salons', ['salon_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint(op.f('uq_service_salon_name'), 'services', ['salon_id', 'name'], postgresql_nulls_not_distinct=False)
    op.alter_column('services', 'price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('services', 'description',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('services', 'name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.alter_column('salons', 'closing_time',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
    op.alter_column('salons', 'opening_time',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
    op.alter_column('salons', 'address_line1',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('salons', 'description',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('bundles', 'bundle_price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('bundles', 'original_price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('bundles', 'description',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_booking_items_booking_id'), table_name='booking_items')
    op.drop_table('booking_items')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_salon_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_customer_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_number'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_date'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_agent_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_salon_slots_status'), table_name='salon_slots')
    op.drop_index(op.f('ix_salon_slots_slot_date'), table_name='salon_slots')
    op.drop_index(op.f('ix_salon_slots_salon_id'), table_name='salon_slots')
    op.drop_index(op.f('ix_salon_slots_agent_id'), table_name='salon_slots')
    op.drop_table('salon_slots')
    # ### end Alembic commands ###
