"""add salon services bundles and agents

Revision ID: b3fdf7a42891
Revises: 9d8714bb5ba7
Create Date: 2026-08-18 16:08:21.330916

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'b3fdf7a42891'
down_revision: Union[str, Sequence[str], None] = '9d8714bb5ba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('address_line1', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('opening_time', sa.String(length=5), nullable=False),
    sa.Column('closing_time', sa.String(length=5), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bundles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('salon_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('original_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('bundle_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bundles_salon_id'), 'bundles', ['salon_id'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('salon_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('salon_id', 'name', name='uq_service_salon_name')
    )
    op.create_index(op.f('ix_services_salon_id'), 'services', ['salon_id'], unique=False)
    op.create_table('bundle_services',
    sa.Column('bundle_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bundle_id'], ['bundles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('bundle_id', 'service_id')
    )
    op.add_column('users', sa.Column('salon_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_salon_id'), 'users', ['salon_id'], unique=False)
    op.create_foreign_key(None, 'users', 'salons', ['salon_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_salon_id'), table_name='users')
    op.drop_column('users', 'salon_id')
    op.drop_table('bundle_services')
    op.drop_index(op.f('ix_services_salon_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_bundles_salon_id'), table_name='bundles')
    op.drop_table('bundles')
    op.drop_table('salons')
    # ### end Alembic commands ###
